 name: DeathCrystals
 version: 0.0.1
 description: Drop DeathCrystals on Death
 author: QuartzDev
 
 main: me.quartzdev.DeathCrystals.Main

 commands:
   deathcrystal:
     description: Commands
   dc:
     description: Alias